import { Product } from '@prisma/client';

export const SEED_PRODUCTS: Partial<Product & { productTypesId?: string[] }>[] =
  [
    {
      id: '0abe1431-d83c-40f1-9d9d-b3ce8f1c0354',
      name: 'Fauteuil de bureau de direction design blanc, bois clair et acier chromé CURVED',
      description:
        "L'élégance du style contemporain et la chaleur du bois ont été associées pour faire du fauteuil de bureau réglable CURVED un siège confortable unique.  Ce grand fauteuil de bureau design, avec ses lignes modernes et son look épuré, équipera un bureau contemporain ou d'inspiration scandinave. Si son dossier haut, son assise large et son piètement métallique en étoile rappellent les fauteuils de direction classiques, sa structure en bois clair et son assise en polyuréthane blanc apportent une touche d'originalité et de style à l'ensemble.  Grâce à son dossier de 58 cm de haut, son assise incurvée, son inclinaison de dossier à 105° et un système de bascule à 130° maximum le fauteuil design CURVED offre un confort optimal. Il est également équipé d'une poignée sous le siège afin de pouvoir régler sa hauteur. Les cinq roulettes qui complètent sa base permettent d'être entièrement mobile. Profitez ainsi d'un espace de travail parfaitement adapté à vos besoins.  Aménagez-vous un bureau 100% pratique et fonctionnel en associant le fauteuil de bureau ergonomique CURVED avec le bureau modulable blanc laqué MAX.",
      slug: 'fauteil-bureau-curved',
      images: [
        'https://www.miliboo.com/fauteuil-de-bureau-de-direction-design-blanc-bois-clair-et-acier-chrome-curved-44764-5c75614fcdd41_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-de-bureau-de-direction-design-blanc-bois-clair-et-acier-chrome-curved-44764-5bdc0e5bbfc84_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-de-bureau-de-direction-design-blanc-bois-clair-et-acier-chrome-curved-44764-5bdc0e5db718c_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-de-bureau-de-direction-design-blanc-bois-clair-et-acier-chrome-curved-44764-5bdc0e5f8d904_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-de-bureau-de-direction-design-blanc-bois-clair-et-acier-chrome-curved-44764-5bdc0e6ba03e5_1200_675_.jpg',
      ],
      price: 419.99,
      quantity: 145,
      categoryId: 'ac41fabd-90a0-4437-9413-c6f372e1aba4',
      productTypesId: ['5d121744-e135-4802-a392-99abd339957b'],
    },
    {
      id: '17cd6741-6113-4d26-86c9-3f457242425b',
      name: 'Bibliothèque design finition bois clair chêne L92 cm EPURE',
      description:
        "Beaucoup d'affaires et peu d'espace ? La bibliothèque EPURE va vous sortir de ce cauchemar.  Avec ses 12 casiers de rangement, cette bibliothèque design finition bois est la solution parfaite pour tous ceux qui cherchent un meuble de rangement pratique et gain de place. Grâce à ses 92 cm de large et ses 2 m de haut, cette bibliothèque haute permet de ranger un maximum d'affaires en prenant un minimum de place. Vous pourrez ordonner vos livres, dossiers, souvenirs et boîtes de rangement dans un même meuble.  Si ses niches de tailles différentes donnent à EPURE une silhouette moderne et design, sa finition bois chêne et ses lignes minimalistes lui permettent d'être installée dans n'importe quelle pièce de la maison. Si ce grand meuble de rangement étagère sera du plus bel effet dans un salon scandinave, on l'envisage tout autant dans aux côtés d'un bureau design au coeur d'un espace de travail contemporain.  La petite astuce déco ? Disposez quelques petits paniers en osier sur certaines étagères pour y déposer vos affaires. Vous donnerez à cette grande bibliothèque (dimensions L92 x P40 x H206 cm) un petit esprit nature, pile dans la tendance.  Bibliothèque design EPURE à assembler. Afin de garantir une stabilité optimale, la bibliothèque design finition bois clair chêne L92 cm EPURE est livrée avec un kit de fixation murale.",
      slug: 'bibliotheque-finition-bois-epure',
      images: [
        'https://www.miliboo.com/bibliotheque-design-finition-bois-clair-chene-l92-cm-epure-48530-64f6e7e86a5eb_1200_675_.jpg',
        'https://www.miliboo.com/bibliotheque-design-finition-bois-clair-chene-l92-cm-epure-48530-5eecd7917fdf9_1200_675_.jpg',
        'https://www.miliboo.com/bibliotheque-design-finition-bois-clair-chene-l92-cm-epure-48530-5eecd78fdee77_1200_675_.jpg',
        'https://www.miliboo.com/bibliotheque-design-finition-bois-clair-chene-l92-cm-epure-48530-60881b0fef75e_1200_675_.jpg',
        'https://www.miliboo.com/bibliotheque-design-finition-bois-clair-chene-l92-cm-epure-48530-6230b6576f8c3_1200_675_.jpg',
      ],
      price: 419.99,
      quantity: 145,
      categoryId: 'e3816067-382c-4c8a-a9d0-d2a527fbf110',
      productTypesId: ['5d121744-e135-4802-a392-99abd339957b'],
    },
    {
      id: '1eb8a338-189e-4e22-b4b7-53a93a542c7f',
      name: 'Fauteuil design en tissu effet velours texturé beige et métal noir GASTON',
      description:
        "Quand le passé se conjugue au présent...  Avec ses lignes joliment rétro et son matelassage original, le fauteuil GASTON réinvente les codes du classique. Ses surpiqûres décoratives sont la signature d'une identité graphique à la fois sobre et affirmée.  Qu'il prenne place dans un séjour ou dans une chambre, ce fauteuil aux volumes harmonieux nous enveloppe de sa douceur. Avec ses accoudoirs évasés et son assise généreusement rembourrée (densité de la mousse 30 kg/m3), il offre un excellent confort au quotidien. Vous appréciez également la texture unique de son tissu effet velours texturé de couleur beige (95% polyester, 5% nylon). Perché sur quatre pieds fuselés en métal noir (H27 cm), ce fauteuil spacieux propose un beau volume d'assise.  Avec sa silhouette faussement classique, le fauteuil design GASTON s'intègre aussi bien dans les espaces contemporains que les intérieurs aux accents rétro. Il s'accordera à merveille à un canapé en tissu de la collection Miliboo.  Livré prêt à monter.",
      slug: 'fauteil-design-gaston',
      images: [
        'https://www.miliboo.com/fauteuil-design-en-tissu-effet-velours-texture-beige-et-metal-noir-gaston-52530-64d257b553f86_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-design-en-tissu-effet-velours-texture-beige-et-metal-noir-gaston-52530-635a625e9dbec_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-design-en-tissu-effet-velours-texture-beige-et-metal-noir-gaston-52530-635a62644b91a_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-design-en-tissu-effet-velours-texture-beige-et-metal-noir-gaston-52530-635a626bcdba4_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-design-en-tissu-effet-velours-texture-beige-et-metal-noir-gaston-52530-635a626fcc78a_1200_675_.jpg',
      ],
      price: 319.99,
      quantity: 11,
      categoryId: '330145b6-142e-47fa-8c85-44c484980b37',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: '4751b584-3a10-46f8-b3fd-104cf78da381',
      name: 'Canapé design 2-3 places en cuir aspect vieilli marron cognac MORRIS',
      description:
        "Un canapé synonyme de (ré)confort...  Le canapé MORRIS affiche un look rétro... Résolument tendance ! Silhouette affirmée qui oscille entre lignes rigoureuses et rebondies, on aime le style subtilement décontracté de ce canapé en cuir marron cognac. Prêt à apporter cachet et caractère à votre salon grâce à son joli revêtement en cuir reconstitué (70% cuir et 30% polyester), ce canapé design en cuir est modernisé par le métal noir. Si la structure souligne l'essentiel, le piètement apporte une belle note de légerté à l'ensemble.  Allié des petits espaces, ce canapé 2-3 places aux dimensions L187 X P84 X H70 cm a été conçu pour s'adapter aux pièces de vie exigües. Voilà de quoi faire le bonheur des intérieurs où chaque m² compte ! Pour un maximum de confort, ce canapé ferme est composé de coussins d'assises à l'épais rembourrage qui mixe mousse polyuréthane HR (densité 30kg/m3) et ouate (densité 300 g/m2).  Canapé fabriqué en Europe et livré prêt à monter.",
      slug: 'canape-design-morris-marron',
      images: [
        'https://www.miliboo.com/canape-design-2-3-places-en-cuir-aspect-vieilli-marron-cognac-morris-53931-64dde0f94a9ff_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-2-3-places-en-cuir-aspect-vieilli-marron-cognac-morris-53931-63c80d9785132_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-2-3-places-en-cuir-aspect-vieilli-marron-cognac-morris-53931-63c80d98d09ea_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-2-3-places-en-cuir-aspect-vieilli-marron-cognac-morris-53931-63c80d9a45fb1_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-2-3-places-en-cuir-aspect-vieilli-marron-cognac-morris-53931-642bfa04cbe17_1200_675_.jpg',
      ],
      price: 799.99,
      quantity: 1200,
      categoryId: '330145b6-142e-47fa-8c85-44c484980b37',
      productTypesId: ['4ec2a100-99c6-44e0-a068-55309b510d77'],
    },
    {
      id: '4fbc38a8-8264-4140-9268-29cffabfafd6',
      name: 'Étagère murale industrielle en bois manguier massif et métal noir L90 cm RACK',
      description:
        "Designée par Caroline Marliac, cette étagère murale en bois massif RACK au style industriel prononcé saura vous séduire par sa personnalité.  Conçue de manière artisanale, cette étagère est fabriquée à la main à partir de matériaux bruts et authentiques : le manguier massif lui apporte une authenticité à tomber et le métal noir perforé donne la touche de caractère indus' qui fait tout son charme. Cette petite tablette murale en bois aux dimensions L90 x P20 x H15 cm offre à elle seule deux espaces de rangements qui accueilleront vos petites plantes et quelques livres de poche agrémentés d'objets déco : une niche ouverte sur la partie basse et une étagère supérieure.   Véritable objet de décoration, cette petite étagère murale en bois et métal noir sera idéale pour ajouter des rangements en hauteur et accentuer la touche déco dans un intérieur à mi-chemin entre esprit nature et style industriel ! On l'associe sans modération à des appliques murales ou kakémonos pour habiller un mur un peu trop sage !",
      slug: 'etagere-murale-rack',
      images: [
        'https://www.miliboo.com/etagere-murale-industrielle-en-bois-manguier-massif-et-metal-noir-l90-cm-rack-45328-5d4186f19ad37_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-industrielle-en-bois-manguier-massif-et-metal-noir-l90-cm-rack-45328-5cd148d644ad6_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-industrielle-en-bois-manguier-massif-et-metal-noir-l90-cm-rack-45328-5cd148d7e2ac4_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-industrielle-en-bois-manguier-massif-et-metal-noir-l90-cm-rack-45328-5cd148d9e2cbf_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-industrielle-en-bois-manguier-massif-et-metal-noir-l90-cm-rack-45328-5cd148dda552c_1200_675_.jpg',
      ],
      price: 99.99,
      quantity: 3000,
      categoryId: 'e3816067-382c-4c8a-a9d0-d2a527fbf110',
      productTypesId: [
        '5d121744-e135-4802-a392-99abd339957b',
        '482bdd8e-19bc-46ee-98ad-29d949f757fa',
      ],
    },
    {
      id: '59a5330e-c8ff-4930-813c-3a3593e0bfd3',
      name: 'Console ouverte design en métal noir L80 cm PODIUM',
      description:
        "La console PODIUM, un meuble aux lignes modernes pour un intérieur organisé avec style !  Association d'un look monochrome et d'une silhouette graphique qui fait tout son charme, cette console en métal noir ne manque pas de style pour séduire de nombreuses ambiances déco ! Si le noir apporte raffinement et élégance, le design déstructuré des plateaux donne à l'ensemble une silhouette originale et moderne. La structure en métal qui compose cette console ouverte a été travaillée tout en finesse pour faire de ce meuble de rangement une pièce de mobilier d'une élégante simplicité.  Si cette petite console en métal noir attirera tous les regards dans une entrée bien agencée, elle pourra, grâce à ses dimensions L80 x P30 x H86 cm, se glisser facilement dans toutes les pièces de la maison. Les différents formats d'étagères permettent de profiter d'espaces de rangement adaptés aux besoins : disposer une boîte, ranger des livres, placer un vase, déposer une paire de chaussures et utiliser le plateau supérieur pour mettre en valeur une lampe à poser... à chaque objets déco ou du quotidien sa place !  Console ouverte design en métal noir L80 cm PODIUM livrée prête à assembler.",
      slug: 'console-podium-metal',
      images: [
        'https://www.miliboo.com/console-ouverte-design-en-metal-noir-l80-cm-podium-48023-60994bb00af56_1200_675_.jpg',
        'https://www.miliboo.com/console-ouverte-design-en-metal-noir-l80-cm-podium-48023-5e71eb2f9cc6b_1200_675_.jpg',
        'https://www.miliboo.com/console-ouverte-design-en-metal-noir-l80-cm-podium-48023-5e71eb38267c2_1200_675_.jpg',
        'https://www.miliboo.com/console-ouverte-design-en-metal-noir-l80-cm-podium-48023-5e71eb473dae5_1200_675_.jpg',
        'https://www.miliboo.com/console-ouverte-design-en-metal-noir-l80-cm-podium-48023-5f18562f78bde_1200_675_.jpg',
      ],
      price: 259.99,
      quantity: 111,
      categoryId: 'e3816067-382c-4c8a-a9d0-d2a527fbf110',
      productTypesId: ['482bdd8e-19bc-46ee-98ad-29d949f757fa'],
    },
    {
      id: '5c924163-24df-4a07-84d5-ea6a8f5a74e9',
      name: 'Chaise de bureau à roulettes design noir, bois foncé noyer et acier chromé ARAMIS',
      description:
        "Son assise et son dossier en polyuréthane noir, facile d'entretien, contrastent agréablement avec sa structure en noyer qui lui assure un look vintage très tendance.   Le fauteuil de bureau design ARAMIS  vous offre un grand confort grâce à son assise et à son dossier rembourrés. Pratique et fonctionnel, il est réglable en hauteur à l'aide d'un vérin pneumatique et peut être déplacé aisément grâce à sa base en étoile chromé montée sur 5 roulettes en nylon très solides. Il est également pivotant.  Associée à un bureau en bois, cette chaise de bureau noire sera la touche design de votre coin bureau !   Chaise de bureau à roulettes design noir, bois foncé noyer et acier chromé ARAMIS à assembler. Montage simple.",
      slug: 'chaise-bureau-aramis',
      images: [
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-noir-bois-fonce-noyer-et-acier-chrome-aramis-42630-5c04f4f73f636_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-noir-bois-fonce-noyer-et-acier-chrome-aramis-42630-5bb76468f019e_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-noir-bois-fonce-noyer-et-acier-chrome-aramis-42630-5bb7646928db5_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-noir-bois-fonce-noyer-et-acier-chrome-aramis-42630-5bb7646941e4c_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-noir-bois-fonce-noyer-et-acier-chrome-aramis-42630-5bb764697493f_1200_675_.jpg',
      ],
      price: 159.79,
      quantity: 900,
      categoryId: 'ac41fabd-90a0-4437-9413-c6f372e1aba4',
      productTypesId: [
        '5d121744-e135-4802-a392-99abd339957b',

        '4ec2a100-99c6-44e0-a068-55309b510d77',
      ],
    },
    {
      id: '5f319a4b-dc16-4bd9-b060-5db5703c3b8f',
      name: 'Chaise design blanc et bois clair BENT',
      description:
        "La collection BENT se décline sous la forme d'une chaise design !   Le modèle BENT se renouvelle dans une version chaise design au look scandi-rétro, ultra tendance ! Tout aussi confortable que le fauteuil de bureau ou la chaise de bar de la même collection, la chaise BENT est composée d'un piètement et d'un dossier en contreplaqué érable laissant apparaître les veines du bois clair. Rendu authentique garanti dans votre pièce de vie. Si le revêtement en polyuréthane blanc modernise l'ensemble et apportera une touche chic et élégante à votre intérieur, cette chaise scandinave saura également vous séduire par sa silhouette unique - savoureux mélange d'inspirations scandinave et vintage. Voilà une chaise design en bois moderne qui sera à l'aise dans de nombreux styles de décoration d'intérieur !  Les courbes atypiques de cette chaise en bois clair et blanc se tiennent prêtent à vous combler de confort ! Sous ses faux airs de fauteuil moderne et cosy, cette chaise avec accoudoirs fera le confort de nombreuses ambiances et univers déco. Chaise de bureau dans un espace de travail design et propice à la concentration, chaise de salle à manger multipliée ou dépareillée autour d'une table à manger design, chaise de réunion confortable ou chaise de salle d'attente chez un professionnel, BENT ne se refuse rien !  Livrée prête à monter. Seul le piètement est à fixer.",
      slug: 'chaise-blanc-bent',
      images: [
        'https://www.miliboo.com/chaise-design-blanc-et-bois-clair-bent-42643-5bb374587bd9e_1200_675_.jpg',
        'https://www.miliboo.com/chaise-design-blanc-et-bois-clair-bent-42643-5bb37457d8aea_1200_675_.jpg',
        'https://www.miliboo.com/chaise-design-blanc-et-bois-clair-bent-42643-5bb3745811119_1200_675_.jpg',
        'https://www.miliboo.com/chaise-design-blanc-et-bois-clair-bent-42643-5bb374582f995_1200_675_.jpg',
        'https://www.miliboo.com/chaise-design-blanc-et-bois-clair-bent-42643-5bb37458441a6_1200_675_.jpg',
      ],
      price: 219.99,
      quantity: 21,
      categoryId: '330145b6-142e-47fa-8c85-44c484980b37',
      productTypesId: ['5d121744-e135-4802-a392-99abd339957b'],
    },
    {
      id: '6cfd167d-5a79-40b8-89b2-bf4ff5770dbb',
      name: 'Fauteuil scandinave en tissu effet velours beige et bois clair massif DERRY',
      description:
        "Envie de quiétude ? Succombez au charme apaisant du fauteuil DERRY.  Aux angles polis et aux lignes organiques, la structure à l'inspiration vintage accueille un siège aux volumes épurés habillé d'un tissu effet velours beige. Lumineuse, cette teinte épurée et intemporelle se prête à merveille au bois clair. Mêlant élégance et simplicité, la silhouette authentique et chaleureuse du fauteuil DERRY trouvera indéniablement sa place dans une chambre ou un salon à la déco scandinave.  Parce qu'un fauteuil scandinave doit rimer avec confort, le cadre robuste en hévéa massif contraste tout en douceur avec le siège profond et le haut dossier. Rembourrée d'une agréable mousse densité 28 kg/m³, l'assise gagne en volume lorsqu'elle est complétée par son coussin d'appoint assorti. Sans fausse note, le piètement arrière légèrement incliné vous promet de doux moments relaxants confortablement installé.  Astuce déco : complétez votre déco avec un tapis, des coussins, des plaids ou encore des rideaux... Ces accessoires textiles seront parfaits pour animer vos espaces tout en renforçant l'ambiance cocooning d'une pièce de vie.  Fauteuil beige et bois livré prêt à monter.",
      slug: 'fauteil-derry-beige',
      images: [
        'https://www.miliboo.com/fauteuil-scandinave-en-tissu-effet-velours-beige-et-bois-clair-massif-derry-51835-634527374fe0b_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-scandinave-en-tissu-effet-velours-beige-et-bois-clair-massif-derry-51835-62cd3cb6dfec0_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-scandinave-en-tissu-effet-velours-beige-et-bois-clair-massif-derry-51835-62cd3cc91a8de_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-scandinave-en-tissu-effet-velours-beige-et-bois-clair-massif-derry-51835-62cd3ccd8b044_1200_675_.jpg',
        'https://www.miliboo.com/fauteuil-scandinave-en-tissu-effet-velours-beige-et-bois-clair-massif-derry-51835-62cd41888b64c_1200_675_.jpg',
      ],
      price: 329.99,
      quantity: 10,
      categoryId: '330145b6-142e-47fa-8c85-44c484980b37',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: '6ded43a7-3343-4552-884d-f2eb0e66e20b',
      name: 'Lit 2 places 140x200 cm en tissu gris NIELS',
      description:
        "Envie d'un lit avec du charme ? Le lit 140 NIELS saura répondre à vos attentes.   Formé par un cadre et une tête de lit en tissu gris (100% polyester), parfaitement dessiné par des courbes légères, ce lit 2 places gris est un véritable intémporel qui se fondra dans le décor d'une petite chambre d'adulte avec une décoration plutôt classique, scandinave ou contemporaine. Son dossier apportera une vraie plus-value design à votre espace nuit mais également maintien et confort pour lire le soir avant de se coucher ou profiter d'un petit-déjeuner au lit !  Conçu en bois, ce lit double est composé d'un sommier 28 lattes en bois courbé. Il accueillera volontiers un confortable matelas 140x200 cm (vendu séparément) pour former un agréable couchage pour 2 personnes.  Livré prêt à monter. Sommier en kit inclus. Matelas non fourni.",
      slug: 'lit-2-places-niels',
      images: [
        'https://www.miliboo.com/lit-2-places-140x200-cm-en-tissu-gris-niels-43023-6554e981b1404_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200-cm-en-tissu-gris-niels-43023-6554e8f66768f_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200-cm-en-tissu-gris-niels-43023-6557462a11580_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200-cm-en-tissu-gris-niels-43023-6554e8fd99083_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200-cm-en-tissu-gris-niels-43023-6554e907e84d6_1200_675_.jpg',
      ],
      price: 369.99,
      quantity: 403,
      categoryId: 'de09946d-0519-40ea-a85a-a0844400b316',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: '6fc3c978-ac25-4656-b263-112408ac3727',
      name: 'Lit 2 places 160x200 cm en bois et tissu beige LYNN',
      description:
        "Le lit 160 LYNN sera parfait pour donner du cachet à votre espace nuit...   Composé d'un cadre en bois et d'une tête de lit capitonné en tissu beige (revêtement 100% polyester) ce lit queen size séduit par son naturel et son aspect chaleureux. Ses lignes modernes en font un lit 2 places parfait pour se créer une ambiance cosy et trendy dans une chambre d'adulte.  Ce lit double est à s'associe avec un matelas 160x200 cm (vendu séparément) pour offrir un confortable couchage pour 2 personnes.  Livré prêt à monter. Sommier inclus. Matelas non fourni.",
      slug: 'lit-2-places-lynn',
      images: [
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-bois-et-tissu-beige-lynn-41740-65d86114e8daf_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-bois-et-tissu-beige-lynn-41740-661f77677e4a8_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-bois-et-tissu-beige-lynn-41740-661f776bab737_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-bois-et-tissu-beige-lynn-41740-661f776e89114_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-bois-et-tissu-beige-lynn-41740-661f7770e8857_1200_675_.jpg',
      ],
      price: 479.99,
      quantity: 203,
      categoryId: 'de09946d-0519-40ea-a85a-a0844400b316',
      productTypesId: ['5d121744-e135-4802-a392-99abd339957b'],
    },
    {
      id: '811c21ed-b17d-403d-8026-3fc181ac609d',
      name: 'Lit 2 places 160x200 cm - Marquise',
      description:
        "Ce lit queen size habillé d'un revêtement en tissu gris (100% polyester) est un vrai cocon agréable et raffiné. Confortable dossier, sommier à lattes avec renfort central pour assurer une distribution uniforme du poids du corps sur toute la surface sans provoquer d'affaissement, ce lit double a été pensé pour votre confort !",
      slug: 'lit-2-places-marquise',
      images: [
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-marquise-25933-5cd54cf3a27f5_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-marquise-25933-5cd54cea0533c_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-marquise-25933-65c0ea8ac0ef7_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-marquise-25933-5cd54ceb5c2f1_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-marquise-25933-5cd54ced26446_1200_675_.jpg',
      ],
      price: 379.99,
      quantity: 12,
      categoryId: 'de09946d-0519-40ea-a85a-a0844400b316',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: '8db0978b-3848-4892-9eb9-08ad30b99ac4',
      name: 'Canapé convertible scandinave 3 places en tissu bleu canard et bois clair OSCAR',
      description:
        "Ce canapé convertible OSCAR est un savant mélange de sobriété et d'élégance pour un salon chic, tendance et pratique !  Avec son dossier capitonné et son coloris bleu, ce canapé ne manque ni de caractère ni de relief. Son piètement unique ajoute une pointe d'élégance et d'originalité à l'ensemble. En effet, ses pieds en frêne sont bruts à l'avant et sont recouverts d'un tissu polyester à l'arrière de celui-ci. Ce décalage crée un effet joli et unique.  Grâce à son revêtement en polyester, ce canapé design est facile d'entretien, idéal pour l'utiliser comme assise au quotidien !  Le canapé lit OSCAR c'est aussi une solution gain de place. En effet, ce canapé se transforme en lit d'appoint en un rien de temps. Il suffit simplement d'abaisser le dossier et de déplier les deux pieds de soutien qui sont cachés à l'intérieur du dossier (accessibles par des zips).   Pour être idéalement placé, ce canapé doit être posé contre un mur (tissu noir sur l'arrière du canapé).  Le canapé scandinave OSCAR existe également en coloris naturel.",
      slug: 'canape-oscar-scandinave',
      images: [
        'https://www.miliboo.com/canape-convertible-scandinave-3-places-en-tissu-bleu-canard-et-bois-clair-oscar-24333-5bfe9b5eddfa7_1200_675_.jpg',
        'https://www.miliboo.com/canape-convertible-scandinave-3-places-en-tissu-bleu-canard-et-bois-clair-oscar-24333-5bb373e25868b_1200_675_.jpg',
        'https://www.miliboo.com/canape-convertible-scandinave-3-places-en-tissu-bleu-canard-et-bois-clair-oscar-24333-5bfe9bc69c68b_1200_675_.jpg',
        'https://www.miliboo.com/canape-convertible-scandinave-3-places-en-tissu-bleu-canard-et-bois-clair-oscar-24333-5bb373e27e927_1200_675_.jpg',
        'https://www.miliboo.com/canape-convertible-scandinave-3-places-en-tissu-bleu-canard-et-bois-clair-oscar-24333-5bb373e29b13c_1200_675_.jpg',
      ],
      price: 369.99,
      quantity: 345,
      categoryId: '330145b6-142e-47fa-8c85-44c484980b37',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: '963a34d4-7257-430d-b749-bf1c7595eb20',
      name: 'Lit 2 places 160x200cm en tissu beige NIELS',
      description:
        "Envie d'un lit avec du charme ? Le lit 160 NIELS saura répondre à vos attentes !  Parfaitement dessiné, ce lit queen size tire son inspiration des pays nordiques. Ses courbes légères et aérées offrent un design unique très subtil. Ce lit beige au revêtement tissu (100% polyester) se fondra parfaitement dans le décor d'une chambre avec une décoration plutôt classique, scandinave ou contemporaine. Ses lignes arrondies lui donnent un style tout en douceur et son piètement en hévéa massif un aspect chaleureux. Confortable et joli, ce lit double trouvera sa place dans une chambre d'adulte et scellera la promesse de nuits paisibles et enchantées...  Ce lit 2 places est composé d'un sommier 28 lattes en bois et pourra accueillir un matelas 160x200 cm (vendu séparément).  Accompagné d'un tapis clair et d'une commode en bois, il fera de la chambre un espace cosy.  Lit 2 places 160x200cm en tissu beige NIELS livré prêt à assembler. Sommier inclus. Matelas non fourni.",
      slug: 'lit-2-places-niels-beige',
      images: [
        'https://www.miliboo.com/lit-2-places-160x200cm-en-tissu-beige-niels-41076-5c35cd73ccc4d_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200cm-en-tissu-beige-niels-41076-655b2ca82dfac_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200cm-en-tissu-beige-niels-41076-655b2c9a04caa_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200cm-en-tissu-beige-niels-41076-655b2cbc85b51_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200cm-en-tissu-beige-niels-41076-655b2eff9d489_1200_675_.jpg',
      ],
      price: 404.99,
      quantity: 6,
      categoryId: 'de09946d-0519-40ea-a85a-a0844400b316',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: '9be2bd90-03d3-4c9c-96d7-39fb47bd3025',
      name: 'Étagère murale ovale en bois massif et métal noir H130 cm HANG',
      description:
        "Avec l'étagère murale HANG, on habille ses murs tout en s'offrant un bel espace de rangement supplémentaire !  L'étagère HANG c'est une forme ovale - ultra déco - et un mélange d'acacia et de métal, rappelant le style déco industriel. Plébiscitée pour la confection de mobilier d'intérieur, l'acacia est une essence naturellement dure et dense particulièrement esthétique. Ce bois imputrescible, se distingue par ses veinures allongées, mais également ses variations de couleurs. Avec le temps, l'exposition à la lumière et sources de chaleur, l'acacia est un bois clair dont le coloris jaune-vert à doré subit une coloration naturelle (brune, rougeoyante, reflets gris).  Le modèle mural HANG n'est pas qu'un objet design. Avec ses cinq étagères, c'est un meuble de rangement mural pratique et fonctionnel. Sa structure en métal et ses éléments en bois massif seront appréciés pour leur solidité.  Le tout a été réuni dans un format XL pile dans la tendance. Avec ses dimensions totales L75 x P20 x H130 cm, cette grande étagère murale ovale en bois et métal noir habillera instanément le mur d'un salon, d'une chambre ou d'une entrée. En l'accompagnant d'un miroir et de quelques cadres, on crée un bel ensemble à disposer dans un couloir ou sur le mur derrière le canapé par exemple.",
      slug: 'etagere-murale-bois-metal-hang',
      images: [
        'https://www.miliboo.com/etagere-murale-ovale-en-bois-massif-et-metal-noir-h130-cm-hang-47599-5ec3df946a9cc_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-ovale-en-bois-massif-et-metal-noir-h130-cm-hang-47599-5e4e69b5e5f2e_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-ovale-en-bois-massif-et-metal-noir-h130-cm-hang-47599-5e4e69b853ad8_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-ovale-en-bois-massif-et-metal-noir-h130-cm-hang-47599-5e4e69b937605_1200_675_.jpg',
        'https://www.miliboo.com/etagere-murale-ovale-en-bois-massif-et-metal-noir-h130-cm-hang-47599-5e4e69be8418f_1200_675_.jpg',
      ],
      price: 269.99,
      quantity: 111,
      categoryId: 'e3816067-382c-4c8a-a9d0-d2a527fbf110',
      productTypesId: [
        '5d121744-e135-4802-a392-99abd339957b',
        '482bdd8e-19bc-46ee-98ad-29d949f757fa',
      ],
    },
    {
      id: 'a03ea90a-f739-4fff-a9e5-17d7c184de20',
      name: 'Bureau avec rangements 3 tiroirs vintage bois foncé noyer L132 cm HALLEN',
      description:
        "Le bureau HALLEN revisite le bureau traditionnel dans une version ultra déco !  Avec HALLEN, le bureau minimaliste, esthétique mais aussi fonctionnel de nos rêves prend vie. Il associe un style rétro et de nombreux rangements dans un format compact, parfait pour les petits espaces. On aime le mélange réussi entre lignes droites et jolies courbes qui lui donne ce style unique. Avec son piètement en noyer massif et son plateau en panneaux de fibres de bois placage noyer laissant apparaître les détails de la matière. Ce petit bureau designen bois aux dimensions L132.3 x P55 x H83.3 cm est une pièce authentique qui ne manque pas de charme !  Aménager un espace de travail parfaitement fonctionnel dans une petite pièce n'a rien d'impossible. Le bureau vintage HALLEN est équipé d'un grand plateau et de trois tiroirs permettant de tout organiser. C'est le meuble parfait pour créer un coin travail confortable et tendance dans une chambre ou un séjour. Un fauteuil de bureau coloré mettra en valeur ses teintes chaleureuses.  Bureau avec rangements 3 tiroirs vintage bois foncé noyer L132 cm HALLEN livré prêt à assembler.",
      slug: 'bureau-hallen',
      images: [
        'https://www.miliboo.com/bureau-avec-rangements-3-tiroirs-vintage-bois-fonce-noyer-l132-cm-hallen-44133-5bb764a78ef40_1200_675_.jpg',
        'https://www.miliboo.com/bureau-avec-rangements-3-tiroirs-vintage-bois-fonce-noyer-l132-cm-hallen-44133-5d4938c960871_1200_675_.jpg',
        'https://www.miliboo.com/bureau-avec-rangements-3-tiroirs-vintage-bois-fonce-noyer-l132-cm-hallen-44133-5d4938db3b0a8_1200_675_.jpg',
        'https://www.miliboo.com/bureau-avec-rangements-3-tiroirs-vintage-bois-fonce-noyer-l132-cm-hallen-44133-5d4938ce68435_1200_675_.jpg',
        'https://www.miliboo.com/bureau-avec-rangements-3-tiroirs-vintage-bois-fonce-noyer-l132-cm-hallen-44133-5d4938d21aff8_1200_675_.jpg',
      ],
      price: 549.99,
      quantity: 1234,
      categoryId: 'ac41fabd-90a0-4437-9413-c6f372e1aba4',
      productTypesId: ['5d121744-e135-4802-a392-99abd339957b'],
    },
    {
      id: 'bdf58b08-4039-435c-9735-cf71e3d832f6',
      name: 'Canapé design 3 places et repose-pieds en tissu effet velours texturé beige CORTO',
      description:
        "La déco se laisse aller à la volupté et à l'originalité... Bullez depuis chez vous avec l'ensemble canapé et pouf repose-pieds CORTO !  Dites adieu aux lignes strictes, arêtes et encoignures, vives les formes ludiques, douces et courbes généreuses. Dans l'air du temps, le « soft living » est bien parti pour bouleverser en profondeur les intérieurs modernes ! Ce canapé arrondi 3 places en tissu effet velours texturé beige et son pouf repose-pieds assorti imposent leur élégance avec douceur. La rondeur est à l'honneur pour apporter du dynamisme et du volume aux espaces trop lisses, un graphisme qui va rompre instantanément avec l'image trop brute et statique d'un décor rectiligne.  Très appréciées pour instaurer une ambiance apaisante, les rondeurs donnent du baume au coeur et invitent au calme... Parfait pour recevoir ou se laisser aller à la détente, future icône de la maison, CORTO invite le bien-être au salon ! Avec un design avant-gardiste, on imagine le canapé moderne en tissu effet velours texturé beige et le pouf repose-pieds CORTO prendre leurs marques dans un salon contemporain et minimaliste.  Parce que les instants de paix ou moments conviviaux sont encore plus appréciés lorsque l'on est bien installé, le duo CORTO ne laisse rien au hasard côté confort ! À la fois chic et cosy, parfait pour profiter d'instants cocooning, ce set - composé d'un grand canapé moderne 3 places (dimensions L210 x P88 x H73.5 cm) et d'un petit pouf repose-pieds (dimensions L70 x P55 x H43 cm) - se distingue par des formes nébuleuses et un gonflant enveloppant.  Garnis d'une agréable mousse, canapé et repose-pieds en tissu beige s'habillent d'un revêtement effet velours texturé. Une trame aussi agréable à l'oeil qu'au toucher qui épouse parfaitement les volumes bien galbés de ce joli tandem ! Si ces deux pièces de mobilier forment le binôme idéal pour se prélasser et étendre ses jambes, elles s'envisagent également dissociées ! Le pouf repose-pieds rectangulaire - facile à déplacer d'une pièce à l'autre - trouvera sa place autant dans une entrée qu'une chambre à coucher et sera l'assise supplémentaire rêvée pour accueillir vos invités. Accentuez l'atmosphère cosy et douillette de votre séjour, grâce à un grand tapis duveteux !  Canapé design 3 places et repose-pieds en tissu effet velours texturé beige CORTO livrés prêt à assembler. Montage simple, seuls les pieds sont à fixer. Le colis du canapé étant volumineux, nous vous conseillons de vérifier que portes et escaliers permettent son passage.",
      slug: 'canape-design-corto-tissu',
      images: [
        'https://www.miliboo.com/canape-design-3-places-et-repose-pieds-en-tissu-effet-velours-texture-beige-corto-56237-662a11995b68b_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-3-places-et-repose-pieds-en-tissu-effet-velours-texture-beige-corto-56237-662657a69d285_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-3-places-et-repose-pieds-en-tissu-effet-velours-texture-beige-corto-56237-662657a7bc267_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-3-places-et-repose-pieds-en-tissu-effet-velours-texture-beige-corto-56237-662657b26b1de_1200_675_.jpg',
        'https://www.miliboo.com/canape-design-3-places-et-repose-pieds-en-tissu-effet-velours-texture-beige-corto-56237-662657bb7b5b5_1200_675_.jpg',
      ],
      price: 1099.99,
      quantity: 120,
      categoryId: '330145b6-142e-47fa-8c85-44c484980b37',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: 'cb46c713-2493-48ab-a1a0-9bdd6cc4c14f',
      name: 'Lit 2 places 140x200cm en bois et tissu gris capitonné LYNN',
      description:
        "Le lit 140 LYNN sera parfait pour donner du cachet à votre chambre à coucher.   Cadre en bois et tête de lit capitonnée en tissu gris (revêtement 100% polyester) forment un tandem élégant et intemporel. On imagine ce lit 2 places camper dans une chambre d'adulte aux couleurs neutres, où il créera une ambiance cosy à souhait....  Ce lit double est à associer à un matelas 140x200 cm (vendu séparément). De quoi disposer d'un confortable couchage pour 2 personne !  Livré prêt à monter. Sommier inclus. Matelas non fourni.",
      slug: 'lit-2-places-bois-lynn-tissu',
      images: [
        'https://www.miliboo.com/lit-2-places-140x200cm-en-bois-et-tissu-gris-capitonne-lynn-41739-5bb3744329b5a_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200cm-en-bois-et-tissu-gris-capitonne-lynn-41739-6557368225e9c_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200cm-en-bois-et-tissu-gris-capitonne-lynn-41739-6557368507fc0_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200cm-en-bois-et-tissu-gris-capitonne-lynn-41739-5bb37442c4c09_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-140x200cm-en-bois-et-tissu-gris-capitonne-lynn-41739-6557367fd5ce0_1200_675_.jpg',
        '',
        '',
      ],
      price: 429.99,
      quantity: 102,
      categoryId: 'de09946d-0519-40ea-a85a-a0844400b316',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: 'cd9b7a53-1ac2-4979-8518-858ecb3c40b8',
      name: 'Lit 2 places 160x200 cm en tissu gris capitonné RILEY',
      description:
        "Avec son look unique, entre le design d'un lit baroque et l'inspiration capitonnée du Chesterfield, ce lit 2 places gris au caractère vintage apportera du cachet à votre chambre à coucher rétro.  Tête et pied de lit capitonnés de ce lit double rappellent le design des intérieurs d'autrefois pour un résultat raffiné et un rendu luxueux. Avec son revêtement en tissu gris au toucher très agréable et sa structure en panneaux de fibres de bois complétée par un sommier à lattes en bois, ce lit queen size est prêt à accueillir un matelas 160x200 cm (vendu séparément). Parfait pour former un confortable couchage pour 2 personnes dans une chambre d'adulte.  Lit 2 places 160x200 cm en tissu gris capitonné RILEY livré prêt à monter. Sommier inclus. Matelas non fourni.",
      slug: 'lit-2-places-riley',
      images: [
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-riley-36329-5cd559856fd61_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-riley-36329-5cd559773c515_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-riley-36329-5cd55978ec260_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-riley-36329-5cd5597adaee4_1200_675_.jpg',
        'https://www.miliboo.com/lit-2-places-160x200-cm-en-tissu-gris-capitonne-riley-36329-5cd5597d122f2_1200_675_.jpg',
      ],
      price: 679.99,
      quantity: 34,
      categoryId: 'de09946d-0519-40ea-a85a-a0844400b316',
      productTypesId: ['523cc088-a57e-483d-8444-f01920124755'],
    },
    {
      id: 'dad4b491-5f0f-49d8-86fb-021a93f02276',
      name: 'Chaise de bureau à roulettes design blanc et acier chromé JESSY',
      description:
        "En réunissant style et confort, le fauteuil de bureau JESSY maîtrise parfaitement ses classiques !  Avec ses petites dimensions et ses cinq roulettes, ce fauteuil de bureau design se glisse partout. Parfaitement mobile et pivotant, c'est un siège pratique pour travailler. Il est équipé d'une assise englobante et rembourrée recouverte de polyuréthane pour un confort d'assise optimal et un rendu élégant. Son dossier permet de profiter d'un excellent maintien. Intemporel et confortable, ce petit fauteuil de bureau confortable et stylé est l'indispensable des espaces de travail de toute la maisonnée.  Robuste et facile d'entretien, la chaise de bureau design JESSY convient aussi bien au bureau des enfants qu'à celui des parents. Grâce à une poignée située sous le siège, vous pouvez régler sa hauteur. Sa teinte indémodable et son magnifique piètement chromé en font un fauteuil à roulettes facile à intégrer dans une chambre ou un séjour. On l'accompagne d'un bureau design pour un espace de travail ultra déco.  Chaise de bureau blanche livrée prête à monter.",
      slug: 'chaise-bureau-jessy-design-blanc',
      images: [
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-blanc-et-acier-chrome-jessy-40620-641db685d7804_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-blanc-et-acier-chrome-jessy-40620-5bb76426c7d2a_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-blanc-et-acier-chrome-jessy-40620-5bb7642712123_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-blanc-et-acier-chrome-jessy-40620-5bb764272a04d_1200_675_.jpg',
        'https://www.miliboo.com/chaise-de-bureau-a-roulettes-design-blanc-et-acier-chrome-jessy-40620-5bb7642740978_1200_675_.jpg',
      ],
      price: 149.99,
      quantity: 28,
      categoryId: 'ac41fabd-90a0-4437-9413-c6f372e1aba4',
      productTypesId: ['4ec2a100-99c6-44e0-a068-55309b510d77'],
    },
  ];
